# Generated by Django 2.2 on 2020-01-29 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0010_book_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_list', models.ManyToManyField(related_name='book_list', to='books.Book')),
                ('currently_reading', models.ManyToManyField(related_name='currently_reading', to='books.Book')),
                ('followers', models.ManyToManyField(related_name='is_following', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wish_list', models.ManyToManyField(related_name='wish_list', to='books.Book')),
            ],
        ),
    ]
