# Generated by Django 2.2 on 2020-01-29 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='book_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='book_list', to='books.Book'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='currently_reading',
            field=models.ManyToManyField(blank=True, null=True, related_name='currently_reading', to='books.Book'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='is_following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wish_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='wish_list', to='books.Book'),
        ),
    ]
