# Generated by Django 2.2 on 2020-01-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200130_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='isfollowing', to='profiles.Profile'),
        ),
    ]
