# Generated by Django 2.2 on 2020-01-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='book',
            name='publish_date',
            field=models.DateTimeField(null=True),
        ),
    ]
