# Generated by Django 2.2 on 2020-01-29 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20200129_2128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
